cabal-version:      3.0
name:               schema-dsl
version:            0.1.0.0
synopsis:           Semantic Dialogue Schema DSL for SSB & Altinn prototyping
license:            MIT
author:             Foran Skjema
maintainer:         hack4ssb2026
build-type:         Simple
extra-doc-files:    README.md

common warnings
    ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints

library
    import:           warnings
    exposed-modules:
        SchemaDSL
        SchemaDSL.Types
        SchemaDSL.Eval
        SchemaDSL.Builders
        SchemaDSL.Examples
        SchemaDSL.Examples.Hackday
        SchemaDSL.Examples.Kostra51
        SchemaDSL.Examples.Byggesak
        SchemaDSL.Examples.ByggesakTrial5
        SchemaDSL.Examples.ByggesakTrial6
        SchemaDSL.Examples.ByggesakTrial7
        SchemaDSL.Examples.MatrixDemo
        SchemaDSL.JSON
        SchemaDSL.MetaSchema
        SchemaDSL.Altinn
        SchemaDSL.Altinn.Types
        SchemaDSL.Altinn.Compile
        SchemaDSL.Altinn.DataModel
        SchemaDSL.Altinn.Inject
    build-depends:
        base >= 4.14 && < 5.0,
        containers >= 0.6,
        aeson >= 2.0,
        aeson-pretty >= 0.8,
        text >= 1.2,
        bytestring >= 0.10,
        vector >= 0.12,
        filepath >= 1.4,
        directory >= 1.3
    hs-source-dirs:   src
    default-language: Haskell2010

executable schema-dsl-cli
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base >= 4.14 && < 5.0,
        schema-dsl,
        bytestring >= 0.10,
        aeson >= 2.0,
        aeson-pretty >= 0.8,
        filepath >= 1.4,
        directory >= 1.3
    hs-source-dirs:   app
    default-language: Haskell2010

test-suite schema-dsl-test
    import:           warnings
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Spec.hs
    build-depends:
        base >= 4.14 && < 5.0,
        containers >= 0.6,
        schema-dsl,
        aeson >= 2.0,
        bytestring >= 0.10,
        text >= 1.2,
        vector >= 0.12
