{-# LANGUAGE OverloadedStrings #-}

module Main where

import System.Environment (getArgs)
import System.Exit (exitFailure)
import qualified Data.ByteString.Lazy as BL
import qualified Data.ByteString.Lazy.Char8 as BLC
import Data.Aeson (Value(..), decode)
import Data.Aeson.Encode.Pretty (encodePretty)
import System.FilePath ((</>))
import System.Directory (doesFileExist)
import SchemaDSL

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--update-baseline"] -> do
      let outPath = "baseline-schema.json"
      BL.writeFile outPath (encodePretty helloWorldDialogue)
      putStrLn $ "Successfully wrote baseline schema to: " ++ outPath

    ["--emit-meta"] -> do
      let outPath = "baseline-schema-meta.json"
      BL.writeFile outPath encodeMetaSchemaPretty
      putStrLn $ "Successfully emitted schema metaschema to: " ++ outPath

    ["--update-all"] -> do
      BL.writeFile "baseline-schema-meta.json" encodeMetaSchemaPretty
      BL.writeFile "baseline-schema.json" (encodePretty helloWorldDialogue)
      BL.writeFile "schemas/hack4ssb-hello.json" (encodePretty helloWorldDialogue)
      BL.writeFile "schemas/hack4ssb-comprehensive.json" (encodePretty syntheticHackDialogue)
      BL.writeFile "schemas/kostra51-kulturminner.json" (encodePretty kostra51KulturminneDialogue)
      BL.writeFile "schemas/kostra51-side1.json" (encodePretty kostra51Side1Dialogue)
      BL.writeFile "schemas/kostra51-side2.json" (encodePretty kostra51Side2Dialogue)
      BL.writeFile "schemas/kostra51-side3.json" (encodePretty kostra51Side3Dialogue)
      BL.writeFile "schemas/kostra51-side4.json" (encodePretty kostra51Side4Dialogue)
      BL.writeFile "schemas/kostra51-side5.json" (encodePretty kostra51Side5Dialogue)
      BL.writeFile "schemas/kostra51-side6.json" (encodePretty kostra51Side6Dialogue)
      BL.writeFile "schemas/kostra51-full.json" (encodePretty kostra51FullDialogue)
      -- Also emit schemas.js bundle for the simulator and visualizer canvases
      let schemasJs = unlines
            [ "// Auto-generated by schema-dsl-cli from SchemaDSL Single Source of Truth"
            , "window.SSB_SCHEMAS = {"
            , "  \"kostra51-full\": " ++ BLC.unpack (encodePretty kostra51FullDialogue) ++ ","
            , "  \"kostra51-side1\": " ++ BLC.unpack (encodePretty kostra51Side1Dialogue) ++ ","
            , "  \"kostra51-side2\": " ++ BLC.unpack (encodePretty kostra51Side2Dialogue) ++ ","
            , "  \"kostra51-side3\": " ++ BLC.unpack (encodePretty kostra51Side3Dialogue) ++ ","
            , "  \"kostra51-side4\": " ++ BLC.unpack (encodePretty kostra51Side4Dialogue) ++ ","
            , "  \"kostra51-side5\": " ++ BLC.unpack (encodePretty kostra51Side5Dialogue) ++ ","
            , "  \"kostra51-side6\": " ++ BLC.unpack (encodePretty kostra51Side6Dialogue) ++ ","
            , "  \"kostra51-kulturminner\": " ++ BLC.unpack (encodePretty kostra51KulturminneDialogue) ++ ","
            , "  \"hack4ssb-comprehensive\": " ++ BLC.unpack (encodePretty syntheticHackDialogue) ++ ","
            , "  \"hack4ssb-hello\": " ++ BLC.unpack (encodePretty helloWorldDialogue)
            , "};"
            ]
      BL.writeFile "../simulator/schemas.js" (BLC.pack schemasJs)
      putStrLn "Successfully updated baseline-schema-meta.json, baseline-schema.json, dsl/schemas/*.json, and simulator/schemas.js!"

    ["--print-baseline"] ->
      BLC.putStrLn (encodePretty helloWorldDialogue)

    ["--print-meta"] ->
      BLC.putStrLn encodeMetaSchemaPretty

    ["--inject-altinn", targetPath] -> do
      injectIntoAltinnApp targetPath helloWorldDialogue

    ["--inject-synthetic", targetPath] -> do
      injectIntoAltinnApp targetPath syntheticHackDialogue

    ["--inject-kostra51", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51KulturminneDialogue

    ["--inject-kostra51-side1", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side1Dialogue

    ["--inject-kostra51-side2", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side2Dialogue

    ["--inject-kostra51-side3", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side3Dialogue

    ["--inject-kostra51-side4", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side4Dialogue

    ["--inject-kostra51-side5", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side5Dialogue

    ["--inject-kostra51-side6", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side6Dialogue

    ["--inject-kostra51-all", targetPath] -> do
      putStrLn $ "Injecting all 6 KOSTRA 51 pages into Altinn app at: " ++ targetPath
      injectIntoAltinnApp targetPath kostra51Side1Dialogue
      injectIntoAltinnApp targetPath kostra51Side2Dialogue
      injectIntoAltinnApp targetPath kostra51Side3Dialogue
      injectIntoAltinnApp targetPath kostra51Side4Dialogue
      injectIntoAltinnApp targetPath kostra51Side5Dialogue
      injectIntoAltinnApp targetPath kostra51Side6Dialogue
      putStrLn "All 6 KOSTRA 51 pages successfully injected into Altinn app!"

    ["--print-altinn-layout"] -> do
      let artifacts = compileToAltinn helloWorldDialogue
      BLC.putStrLn (encodePretty (pageLayout artifacts))

    ["--print-synthetic-layout"] -> do
      let artifacts = compileToAltinn syntheticHackDialogue
      BLC.putStrLn (encodePretty (pageLayout artifacts))

    ["--print-kostra51-layout"] -> do
      let artifacts = compileToAltinn kostra51KulturminneDialogue
      BLC.putStrLn (encodePretty (pageLayout artifacts))

    ["--reorder-evolution", targetPath] -> do
      let settingsPath = targetPath </> "App" </> "ui" </> "mainlayout" </> "Settings.json"
      exists <- doesFileExist settingsPath
      if exists
        then do
          content <- BL.readFile settingsPath
          case decode (stripBOM content) of
            Just (Object obj) -> do
              let updated = enforceEvolutionPageOrder obj
              BL.writeFile settingsPath (encodePretty (Object updated))
              putStrLn $ "Successfully reordered pages in " ++ settingsPath ++ " according to schema evolution!"
            _ -> do
              putStrLn $ "Error: Failed to parse Settings.json at " ++ settingsPath
              exitFailure
        else do
          putStrLn $ "Error: Settings.json does not exist at " ++ settingsPath
          exitFailure

    _ -> do
      putStrLn "Dialogue Schema DSL CLI"
      putStrLn "Usage:"
      putStrLn "  cabal run schema-dsl-cli -- --update-baseline       # Write dsl/baseline-schema.json"
      putStrLn "  cabal run schema-dsl-cli -- --emit-meta             # Write dsl/baseline-schema-meta.json"
      putStrLn "  cabal run schema-dsl-cli -- --update-all            # Write both meta and baseline schemas"
      putStrLn "  cabal run schema-dsl-cli -- --inject-altinn <DIR>   # Compile and inject baseline into Altinn App repo"
      putStrLn "  cabal run schema-dsl-cli -- --inject-synthetic <DIR># Compile and inject comprehensive synthetic schema into Altinn App repo"
      putStrLn "  cabal run schema-dsl-cli -- --reorder-evolution <DIR> # Reorder Altinn pages by schema evolution progression"
      putStrLn "  cabal run schema-dsl-cli -- --print-altinn-layout   # Print compiled Altinn layout JSON"
      putStrLn "  cabal run schema-dsl-cli -- --print-synthetic-layout# Print compiled synthetic Altinn layout JSON"
      putStrLn "  cabal run schema-dsl-cli -- --print-baseline        # Print baseline JSON to stdout"
      putStrLn "  cabal run schema-dsl-cli -- --print-meta            # Print meta schema JSON to stdout"
      exitFailure
