{-# LANGUAGE OverloadedStrings #-}

module Main where

import System.Environment (getArgs)
import System.Exit (exitFailure)
import qualified Data.ByteString.Char8 as BS
import qualified Data.ByteString.Lazy as BL
import qualified Data.ByteString.Lazy.Char8 as BLC
import Data.Aeson (Value(..), decode)
import Data.Aeson.Encode.Pretty (encodePretty)
import System.FilePath ((</>))
import System.Directory (doesFileExist)
import Data.Bits (xor)
import Data.Word (Word32)
import Numeric (showHex)
import SchemaDSL

main :: IO ()
main = do
  args <- getArgs
  case args of
    -- Any paged inject command followed by --set-app-title also sets the app title
    [cmd, targetPath, "--set-app-title"] | Just d <- lookup cmd pagedInjectCommands -> do
      injectIntoAltinnAppPaged targetPath d
      setAppTitle targetPath d

    ["--update-baseline"] -> do
      let outPath = "baseline-schema.json"
      BL.writeFile outPath (encodePretty helloWorldDialogue)
      putStrLn $ "Successfully wrote baseline schema to: " ++ outPath

    ["--emit-meta"] -> do
      let outPath = "baseline-schema-meta.json"
      BL.writeFile outPath encodeMetaSchemaPretty
      putStrLn $ "Successfully emitted schema metaschema to: " ++ outPath

    ["--update-all"] -> do
      BL.writeFile "baseline-schema-meta.json" encodeMetaSchemaPretty
      BL.writeFile "baseline-schema.json" (encodePretty helloWorldDialogue)
      BL.writeFile "schemas/hack4ssb-hello.json" (encodePretty helloWorldDialogue)
      BL.writeFile "schemas/hack4ssb-comprehensive.json" (encodePretty syntheticHackDialogue)
      BL.writeFile "schemas/hack4ssb-rules.json" (encodePretty rulesDemoDialogue)
      BL.writeFile "schemas/hack4ssb-matrix.json" (encodePretty matrixDemoDialogue)
      BL.writeFile "schemas/kostra51-kulturminner.json" (encodePretty kostra51KulturminneDialogue)
      BL.writeFile "schemas/kostra51-side1.json" (encodePretty kostra51Side1Dialogue)
      BL.writeFile "schemas/kostra51-side2.json" (encodePretty kostra51Side2Dialogue)
      BL.writeFile "schemas/kostra51-side3.json" (encodePretty kostra51Side3Dialogue)
      BL.writeFile "schemas/kostra51-side4.json" (encodePretty kostra51Side4Dialogue)
      BL.writeFile "schemas/kostra51-side5.json" (encodePretty kostra51Side5Dialogue)
      BL.writeFile "schemas/kostra51-side6.json" (encodePretty kostra51Side6Dialogue)
      BL.writeFile "schemas/kostra51-full.json" (encodePretty kostra51FullDialogue)
      BL.writeFile "schemas/trial1-byggesak.json" (encodePretty trial1ByggesakDialogue)
      BL.writeFile "schemas/trial2-byggesak.json" (encodePretty trial2ByggesakDialogue)
      BL.writeFile "schemas/trial3-byggesak.json" (encodePretty trial3ByggesakDialogue)
      BL.writeFile "schemas/trial4-byggesak.json" (encodePretty trial4ByggesakDialogue)
      BL.writeFile "schemas/trial5-byggesak.json" (encodePretty trial5ByggesakDialogue)
      BL.writeFile "schemas/trial6-byggesak.json" (encodePretty trial6ByggesakDialogue)
      -- Also emit schemas.js bundle for the simulator and visualizer canvases
      let schemasJs = unlines
            [ "// Auto-generated by schema-dsl-cli from SchemaDSL Single Source of Truth"
            , "window.SSB_SCHEMAS = {"
            , "  \"hack4ssb-matrix\": " ++ BLC.unpack (encodePretty matrixDemoDialogue) ++ ","
            , "  \"hack4ssb-rules\": " ++ BLC.unpack (encodePretty rulesDemoDialogue) ++ ","
            , "  \"trial6-byggesak\": " ++ BLC.unpack (encodePretty trial6ByggesakDialogue) ++ ","
            , "  \"trial5-byggesak\": " ++ BLC.unpack (encodePretty trial5ByggesakDialogue) ++ ","
            , "  \"trial4-byggesak\": " ++ BLC.unpack (encodePretty trial4ByggesakDialogue) ++ ","
            , "  \"trial3-byggesak\": " ++ BLC.unpack (encodePretty trial3ByggesakDialogue) ++ ","
            , "  \"trial2-byggesak\": " ++ BLC.unpack (encodePretty trial2ByggesakDialogue) ++ ","
            , "  \"trial1-byggesak\": " ++ BLC.unpack (encodePretty trial1ByggesakDialogue) ++ ","
            , "  \"kostra51-full\": " ++ BLC.unpack (encodePretty kostra51FullDialogue) ++ ","
            , "  \"kostra51-side1\": " ++ BLC.unpack (encodePretty kostra51Side1Dialogue) ++ ","
            , "  \"kostra51-side2\": " ++ BLC.unpack (encodePretty kostra51Side2Dialogue) ++ ","
            , "  \"kostra51-side3\": " ++ BLC.unpack (encodePretty kostra51Side3Dialogue) ++ ","
            , "  \"kostra51-side4\": " ++ BLC.unpack (encodePretty kostra51Side4Dialogue) ++ ","
            , "  \"kostra51-side5\": " ++ BLC.unpack (encodePretty kostra51Side5Dialogue) ++ ","
            , "  \"kostra51-side6\": " ++ BLC.unpack (encodePretty kostra51Side6Dialogue) ++ ","
            , "  \"kostra51-kulturminner\": " ++ BLC.unpack (encodePretty kostra51KulturminneDialogue) ++ ","
            , "  \"hack4ssb-comprehensive\": " ++ BLC.unpack (encodePretty syntheticHackDialogue) ++ ","
            , "  \"hack4ssb-hello\": " ++ BLC.unpack (encodePretty helloWorldDialogue)
            , "};"
            ]
      BL.writeFile "../simulator/schemas.js" (BLC.pack schemasJs)
      -- Version stamp so browsers load the new bundle instead of a cached copy
      let version = contentHash (BLC.pack schemasJs)
      mapM_ (stampSchemasScript version) ["../simulator/index.html", "../simulator/dsl-visualizer.html"]
      putStrLn "Successfully updated baseline-schema-meta.json, baseline-schema.json, dsl/schemas/*.json, and simulator/schemas.js!"

    ["--print-baseline"] ->
      BLC.putStrLn (encodePretty helloWorldDialogue)

    ["--print-meta"] ->
      BLC.putStrLn encodeMetaSchemaPretty

    ["--inject-altinn", targetPath] -> do
      injectIntoAltinnApp targetPath helloWorldDialogue

    ["--inject-matrix-demo", targetPath] -> do
      injectIntoAltinnAppPaged targetPath matrixDemoDialogue

    ["--inject-rules", targetPath] -> do
      injectIntoAltinnApp targetPath rulesDemoDialogue

    ["--inject-synthetic", targetPath] -> do
      injectIntoAltinnApp targetPath syntheticHackDialogue

    ["--inject-kostra51", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51KulturminneDialogue

    ["--inject-kostra51-side1", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side1Dialogue

    ["--inject-kostra51-side2", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side2Dialogue

    ["--inject-kostra51-side3", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side3Dialogue

    ["--inject-kostra51-side4", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side4Dialogue

    ["--inject-kostra51-side5", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side5Dialogue

    ["--inject-kostra51-side6", targetPath] -> do
      injectIntoAltinnApp targetPath kostra51Side6Dialogue

    ["--inject-kostra51-all", targetPath] -> do
      putStrLn $ "Injecting all 6 KOSTRA 51 pages into Altinn app at: " ++ targetPath
      injectIntoAltinnApp targetPath kostra51Side1Dialogue
      injectIntoAltinnApp targetPath kostra51Side2Dialogue
      injectIntoAltinnApp targetPath kostra51Side3Dialogue
      injectIntoAltinnApp targetPath kostra51Side4Dialogue
      injectIntoAltinnApp targetPath kostra51Side5Dialogue
      injectIntoAltinnApp targetPath kostra51Side6Dialogue
      putStrLn "All 6 KOSTRA 51 pages successfully injected into Altinn app!"

    ["--inject-trial1", targetPath] -> do
      putStrLn $ "Injecting Trial 1 Byggesak into Altinn app at: " ++ targetPath
      injectIntoAltinnApp targetPath trial1ByggesakDialogue
      putStrLn "Trial 1 Byggesak successfully injected into Altinn app!"

    ["--inject-trial2", targetPath] -> do
      putStrLn $ "Injecting Trial 2 Byggesak into Altinn app at: " ++ targetPath
      injectIntoAltinnApp targetPath trial2ByggesakDialogue
      putStrLn "Trial 2 Byggesak successfully injected into Altinn app!"

    ["--inject-trial3", targetPath] -> do
      putStrLn $ "Injecting Trial 3 Byggesak into Altinn app at: " ++ targetPath
      injectIntoAltinnApp targetPath trial3ByggesakDialogue
      putStrLn "Trial 3 Byggesak successfully injected into Altinn app!"

    ["--inject-trial4", targetPath] -> do
      putStrLn $ "Injecting Trial 4 Byggesak into Altinn app at: " ++ targetPath
      injectIntoAltinnApp targetPath trial4ByggesakDialogue
      putStrLn "Trial 4 Byggesak successfully injected into Altinn app!"

    ["--inject-trial6", targetPath] -> do
      putStrLn $ "Injecting Trial 6 Byggesak into Altinn app at: " ++ targetPath
      injectIntoAltinnAppPaged targetPath trial6ByggesakDialogue
      putStrLn "Trial 6 Byggesak successfully injected into Altinn app!"

    ["--inject-trial5", targetPath] -> do
      putStrLn $ "Injecting Trial 5 Byggesak into Altinn app at: " ++ targetPath
      injectIntoAltinnAppPaged targetPath trial5ByggesakDialogue
      putStrLn "Trial 5 Byggesak successfully injected into Altinn app!"

    ["--print-altinn-layout"] -> do
      let artifacts = compileToAltinn helloWorldDialogue
      BLC.putStrLn (encodePretty (pageLayout artifacts))

    ["--print-synthetic-layout"] -> do
      let artifacts = compileToAltinn syntheticHackDialogue
      BLC.putStrLn (encodePretty (pageLayout artifacts))

    ["--print-kostra51-layout"] -> do
      let artifacts = compileToAltinn kostra51KulturminneDialogue
      BLC.putStrLn (encodePretty (pageLayout artifacts))

    ["--reorder-evolution", targetPath] -> do
      let settingsPath = targetPath </> "App" </> "ui" </> "mainlayout" </> "Settings.json"
      exists <- doesFileExist settingsPath
      if exists
        then do
          content <- BL.readFile settingsPath
          case decode (stripBOM content) of
            Just (Object obj) -> do
              let updated = enforceEvolutionPageOrder obj
              BL.writeFile settingsPath (encodePretty (Object updated))
              putStrLn $ "Successfully reordered pages in " ++ settingsPath ++ " according to schema evolution!"
            _ -> do
              putStrLn $ "Error: Failed to parse Settings.json at " ++ settingsPath
              exitFailure
        else do
          putStrLn $ "Error: Settings.json does not exist at " ++ settingsPath
          exitFailure

    _ -> do
      putStrLn "Dialogue Schema DSL CLI"
      putStrLn "Usage:"
      putStrLn "  cabal run schema-dsl-cli -- --update-baseline       # Write dsl/baseline-schema.json"
      putStrLn "  cabal run schema-dsl-cli -- --emit-meta             # Write dsl/baseline-schema-meta.json"
      putStrLn "  cabal run schema-dsl-cli -- --update-all            # Write both meta and baseline schemas"
      putStrLn "  cabal run schema-dsl-cli -- --inject-altinn <DIR>   # Compile and inject baseline into Altinn App repo"
      putStrLn "  cabal run schema-dsl-cli -- --inject-synthetic <DIR># Compile and inject comprehensive synthetic schema into Altinn App repo"
      putStrLn "  cabal run schema-dsl-cli -- --inject-trial5 <DIR>    # Inject Byggesak Trial 5, one Altinn page per bolk"
      putStrLn "  cabal run schema-dsl-cli -- --inject-trial6 <DIR>    # Inject Byggesak Trial 6, one Altinn page per bolk"
      putStrLn "      (add --set-app-title after <DIR> to --inject-trial5/6 or --inject-matrix-demo to set the app title from the form name)"
      putStrLn "  cabal run schema-dsl-cli -- --inject-matrix-demo <DIR># Inject the matrix demo, one Altinn page per bolk"
      putStrLn "  cabal run schema-dsl-cli -- --reorder-evolution <DIR> # Reorder Altinn pages by schema evolution progression"
      putStrLn "  cabal run schema-dsl-cli -- --print-altinn-layout   # Print compiled Altinn layout JSON"
      putStrLn "  cabal run schema-dsl-cli -- --print-synthetic-layout# Print compiled synthetic Altinn layout JSON"
      putStrLn "  cabal run schema-dsl-cli -- --print-baseline        # Print baseline JSON to stdout"
      putStrLn "  cabal run schema-dsl-cli -- --print-meta            # Print meta schema JSON to stdout"
      exitFailure

-- | FNV-1a hash of the content, as hex: changes only when the content changes
contentHash :: BL.ByteString -> String
contentHash = flip showHex "" . BL.foldl' step (2166136261 :: Word32)
  where
    step h b = (h `xor` fromIntegral b) * 16777619

-- | Point the page's <script src="schemas.js..."> at schemas.js?v=<version>
stampSchemasScript :: String -> FilePath -> IO ()
stampSchemasScript version path = do
  exists <- doesFileExist path
  if not exists
    then putStrLn $ "  [!] Warning: " ++ path ++ " not found"
    else do
      html <- BS.readFile path
      let (before, rest) = BS.breakSubstring "<script src=\"schemas.js" html
          (_, after) = BS.breakSubstring "\"></script>" rest
      if BS.null rest || BS.null after
        then putStrLn $ "  [!] Warning: no schemas.js script tag in " ++ path
        else do
          BS.writeFile path (BS.concat [before, "<script src=\"schemas.js?v=", BS.pack version, after])
          putStrLn $ "  [+] Stamped schemas.js?v=" ++ version ++ " in " ++ path

-- | Inject commands that compile one Altinn page per bolk
pagedInjectCommands :: [(String, Dialogue)]
pagedInjectCommands =
  [ ("--inject-trial5", trial5ByggesakDialogue)
  , ("--inject-trial6", trial6ByggesakDialogue)
  , ("--inject-matrix-demo", matrixDemoDialogue)
  ]
