name:                 schema-dsl
version:              0.1.0.0
visibility:           public
id:                   schema-dsl-0.1.0.0-inplace
key:                  schema-dsl-0.1.0.0-inplace
license:              MIT
maintainer:           hack4ssb2026
author:               Foran Skjema
synopsis:             Semantic Dialogue Schema DSL for SSB & Altinn prototyping
abi:                  inplace
exposed:              True
exposed-modules:      SchemaDSL SchemaDSL.JSON SchemaDSL.Types
import-dirs:
    /Users/jcb/src/hack4ssb2026/dsl/dist-newstyle/build/aarch64-osx/ghc-9.10.3/schema-dsl-0.1.0.0/build

library-dirs:
    /Users/jcb/src/hack4ssb2026/dsl/dist-newstyle/build/aarch64-osx/ghc-9.10.3/schema-dsl-0.1.0.0/build

library-dirs-static:
    /Users/jcb/src/hack4ssb2026/dsl/dist-newstyle/build/aarch64-osx/ghc-9.10.3/schema-dsl-0.1.0.0/build

dynamic-library-dirs:
    /Users/jcb/src/hack4ssb2026/dsl/dist-newstyle/build/aarch64-osx/ghc-9.10.3/schema-dsl-0.1.0.0/build

data-dir:             /Users/jcb/src/hack4ssb2026/dsl/.
hs-libraries:         HSschema-dsl-0.1.0.0-inplace
depends:
    sn-2.3.2.0-7cfe5eac base-4.20.2.0-754f bytestring-0.12.2.0-84fd
    text-2.1.3-c55a

haddock-interfaces:
    /Users/jcb/src/hack4ssb2026/dsl/dist-newstyle/build/aarch64-osx/ghc-9.10.3/schema-dsl-0.1.0.0/doc/html/schema-dsl/schema-dsl.haddock

haddock-html:
    /Users/jcb/src/hack4ssb2026/dsl/dist-newstyle/build/aarch64-osx/ghc-9.10.3/schema-dsl-0.1.0.0/doc/html/schema-dsl
